<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use App\Models\Interest;

class InterestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        Interest::truncate();
        Schema::enableForeignKeyConstraints();

        $interests = array(
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'master_parent_id' => NULL, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now() , 'slug' => 'traveling'),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'master_parent_id' => NULL, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => 'music'),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'master_parent_id' => NULL, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => 'books'),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'master_parent_id' => NULL, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => 'film'),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'master_parent_id' => NULL, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => 'hobbies'),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'master_parent_id' => NULL, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => 'childhood-game'),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'master_parent_id' => NULL, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => 'sports'),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'master_parent_id' => NULL, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => 'actors'),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'master_parent_id' => NULL, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => 'singers'),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'master_parent_id' => NULL, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => 'food'),

            // Favourite Actors (Male / Female)
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 8, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 8, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // Favourite Singers (Male / Female)
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 9, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 9, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // Favourite Singers (Veg / Non Veg / Desserts)
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),

            // Idea Of Traveling
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'master_parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'master_parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'master_parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'master_parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'master_parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'master_parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'master_parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'master_parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'master_parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'master_parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // My Kind Of Music
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // Book Reading Preference
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'master_parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // Film & TV Type
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'master_parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // Hobbies & Pass Time
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'master_parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // Favourite Childhood Game
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'master_parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // Favourite Sports
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'master_parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // Favourite Actors (Male)
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // Favourite Actors (Female)
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'master_parent_id' => 8, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // Favourite Singers (Male)
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // Favourite Singers (FeMale)
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'master_parent_id' => 9, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // Food I love to eat (Veg)
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // Food I love to eat (Non Veg)
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // Food I love to eat (Desserts)
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now(), 'slug' => NULL),

            // // Food I love to eat (Refreshments)
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 10, 'master_parent_id' => 10, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
        );

        Interest::insert($interests);
    }
}
