<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use App\Models\Interest;

class InterestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        Interest::truncate();
        Schema::enableForeignKeyConstraints();

        $interests = array(
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => NULL, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),

            // Idea Of Traveling
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 1, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),

            // My Kind Of Music
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 2, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),

            // Book Reading Preference
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 3, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),

            // Film & TV Type
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 4, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),

            // Hobbies & Pass Time
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 5, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),

            // Favourite Childhood Game
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 6, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),

            // Favourite Sports
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),
            array('custom_id' => getUniqueString('interests'), 'parent_id' => 7, 'location_id' => 1, 'level' => 2, 'created_at' => now(), 'updated_at' => now()),

            // Food I Love (Veg)
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 11, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),

            // // Food I Love (Non Veg)
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 12, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),

            // // Food I Love (Desserts)
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 13, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),

            // // Food I Love (Refreshments)
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 14, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),

            // // Favourite Actors (Male)
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 15, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),

            // // Favourite Actors (Female)
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 16, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),

            // // Favourite Singers (Male)
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 17, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),

            // // Favourite Singers (FeMale)
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 18, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 18, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 18, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 18, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 18, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 18, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 18, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 18, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 18, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 18, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 18, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 18, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
            // array('custom_id' => getUniqueString('interests'), 'parent_id' => 18, 'location_id' => 1, 'level' => 3, 'created_at' => now(), 'updated_at' => now()),
        );

        Interest::insert($interests);
    }
}
