<?php

namespace Database\Seeders;

use App\Models\ProfileDetail;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ProfileDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        ProfileDetail::truncate();
        Schema::enableForeignKeyConstraints();

        $profile_detail = array(
            array('slug' => "relationship-status-single", 'attribute' => "relationship_status", 'type' => "string"),
            array('slug' => "relationship-status-single-with-kids", 'attribute' => "relationship_status", 'type' => "string"),
            array('slug' => "relationship-status-divorced", 'attribute' => "relationship_status", 'type' => "string"),
            array('slug' => "relationship-status-divorced-with-kids", 'attribute' => "relationship_status", 'type' => "string"),
            array('slug' => "relationship-status-widowed", 'attribute' => "relationship_status", 'type' => "string"),
            array('slug' => "relationship-status-widowed-with-kids", 'attribute' => "relationship_status", 'type' => "string"),
            array('slug' => "relationship-status-separated-with-kids", 'attribute' => "relationship_status", 'type' => "string"),

            array('slug' => "you-are-here-friendship", 'attribute' => "you_are_here", 'type' => "string"),
            array('slug' => "you-are-here-relationship", 'attribute' => "you_are_here", 'type' => "string"),
            array('slug' => "you-are-here-casual", 'attribute' => "you_are_here", 'type' => "string"),
            array('slug' => "you-are-here-both", 'attribute' => "you_are_here", 'type' => "string"),
            array('slug' => "you-are-here-dont-know", 'attribute' => "you_are_here", 'type' => "string"),

            array('slug' => "food-preference-veg", 'attribute' => "food_preference", 'type' => "string"),
            array('slug' => "food-preference-non-veg", 'attribute' => "food_preference", 'type' => "string"),
            array('slug' => "food-preference-vegan", 'attribute' => "food_preference", 'type' => "string"),
            array('slug' => "food-preference-eggetarian", 'attribute' => "food_preference", 'type' => "string"),

            array('slug' => "drinking-frequently", 'attribute' => "drinking", 'type' => "string"),
            array('slug' => "drinking-socially", 'attribute' => "drinking", 'type' => "string"),
            array('slug' => "drinking-never", 'attribute' => "drinking", 'type' => "string"),

            array('slug' => "smoking-frequently", 'attribute' => "smoking", 'type' => "string"),
            array('slug' => "smoking-socially", 'attribute' => "smoking", 'type' => "string"),
            array('slug' => "smoking-never", 'attribute' => "smoking", 'type' => "string"),

            array('slug' => "sun-sign-aries", 'attribute' => "sun_sign", 'type' => "string"),
            array('slug' => "sun-sign-taurus", 'attribute' => "sun_sign", 'type' => "string"),
            array('slug' => "sun-sign-gemini", 'attribute' => "sun_sign", 'type' => "string"),
            array('slug' => "sun-sign-cancer", 'attribute' => "sun_sign", 'type' => "string"),
            array('slug' => "sun-sign-leo", 'attribute' => "sun_sign", 'type' => "string"),
            array('slug' => "sun-sign-virgo", 'attribute' => "sun_sign", 'type' => "string"),
            array('slug' => "sun-sign-libra", 'attribute' => "sun_sign", 'type' => "string"),
            array('slug' => "sun-sign-scorpio", 'attribute' => "sun_sign", 'type' => "string"),
            array('slug' => "sun-sign-sagittarius", 'attribute' => "sun_sign", 'type' => "string"),
            array('slug' => "sun-sign-capricorn", 'attribute' => "sun_sign", 'type' => "string"),
            array('slug' => "sun-sign-aquarius", 'attribute' => "sun_sign", 'type' => "string"),
            array('slug' => "sun-sign-pisces", 'attribute' => "sun_sign", 'type' => "string"),

            array('slug' => "religion-hindu", 'attribute' => "religion", 'type' => "string"),
            array('slug' => "religion-christian", 'attribute' => "religion", 'type' => "string"),
            array('slug' => "religion-muslim", 'attribute' => "religion", 'type' => "string"),
            array('slug' => "religion-sikh", 'attribute' => "religion", 'type' => "string"),
            array('slug' => "religion-jain", 'attribute' => "religion", 'type' => "string"),
            array('slug' => "religion-parsi", 'attribute' => "religion", 'type' => "string"),
            array('slug' => "religion-buddhist", 'attribute' => "religion", 'type' => "string"),
            array('slug' => "religion-jewish", 'attribute' => "religion", 'type' => "string"),
            array('slug' => "religion-spiritual", 'attribute' => "religion", 'type' => "string"),
            array('slug' => "religion-atheist", 'attribute' => "religion", 'type' => "string"),
            array('slug' => "religion-agnostic", 'attribute' => "religion", 'type' => "string"),
            array('slug' => "religion-other", 'attribute' => "religion", 'type' => "string"),

            array('slug' => "community-agri", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-ahom", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-anavil-brahmin", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-arora", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-arya-vysya", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-agarwal", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-bahi", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-baidya", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-baishnab", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-baishya", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-balija-naidu", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-baniya", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-barujibi", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-bengali-brahmin", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-bengali-kayastha", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-besta", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-bhandari", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-bhatia", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-bhovi", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-billava", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-born-again", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-brahmin", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-brahmin-bhumihar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-brahmin-deshastha", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-brahmin-goswami", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-brahmin-kanada-madhva", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-brahmin-karhade", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-brahmin-kokanastha", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-brahmin-smartha", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-brahmin-tyagi", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-brahmin-vaidiki", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-bunt", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-catholic", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-chambhar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-chaurasia", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-dawoodi-bohra", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-desai", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-devanga", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-dhangar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-dheevara", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-dhobi", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-ediga", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-ehle", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-evangelical", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-ezhava", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-ezhuthachan", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-ganiga", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-garhwali-brahmins", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-garhwali-rajput", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-gomantak-maratha", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-goud", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-gounder", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-gour-brahmin", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-gowd-saraswat Brahmin", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-gowda", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-gramani", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-gudia", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-gujarati-brahmin", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-gujarati-lohana", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-gujarati-vaishnav", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-gupta", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-hadith", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-havyaka-brahmin", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-hindi-agarwal", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-hindi-arora", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-hindi-brahmin", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-hindi-kayastha", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-hindi-khatri", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-Hindi-rajput", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-iyengar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-iyer", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-jacobite", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-jain", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-jain-digambar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-jain-shwetamber", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-jaiswal", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-jat", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kaibarta", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kalar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kalinga-vysya", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kalita", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kamboj", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kamma", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kannada-bunt", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kannada-lingayat", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kapu", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kapu-naidu", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-karana", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kashyap", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-khandelwal", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-koli", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kongu-vellala-gounder", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kori", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kshatriya", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kulalar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kumbhakar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kumbhar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kumhar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kunbi", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kuruba", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kuruhina-shetty", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-kayastha", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-khatri", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-leva", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-leva-patil", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-lingayat", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-lohana", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-madiga", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-mahar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-maharashtrian", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-maheshwari", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-mahishya", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-mala", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-malayalam-menon", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-malayalam-nair", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-malayalam-nambiar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-malayalam-pillai", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-mangalorean", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-marathi-brahmin", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-marathi-ckp", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-marthoma", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-marwari", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-marwari-agarwal", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-maurya", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-meenavar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-memon", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-menon", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-mogaveera", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-mudaliar-arcot", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-mudiraj", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-muthuraja", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-maratha", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-nadar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-naicker", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-naidu", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-nambiar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-nepali", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-nair", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-oswal", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-panchal", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-panicker", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-patel", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-patel-kadava", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-patel-leva", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-perika", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-pillai", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-prajapati", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-protestant", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-punjabi", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-punjabi-agarwal", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-punjabi-arora", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-punjabi-brahmin", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-punjabi-brahmin Saraswat", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-punjabi-khatri", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-punjabi-kshatriya", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-rajaka", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-rajput-lodhi", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-ramdasi", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-ramgharia", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-ravidasia", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-reddy", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-roman-catholic", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-rajput", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sadgop", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sahu", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-saini", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-saiva", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-saliya", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-saraswat", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-scheduled-caste", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-scheduled-tribe", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-setti", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-shimpi", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sikh", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sikh-gursikh", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sikh-kesadhari", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sikh-khatri", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sikh-kshatriya", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sikh-labana", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sikh-ramdasia", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sikh-ravidasia", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sikh-saini", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sindhi-amil", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sindhi-baibhand", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sindhi-larkana", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sindhi-sahiti", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sindhi-sakkhar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sindhi-shikarpuri", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sonar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sozhiya-vellalar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sutar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-syrian", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-shia", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-sunni", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-tamil-brahmin", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-tamil-brahmin Iyer", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-tamil-mudaliar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-telegu-brahmin", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-teli", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-thakur", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-thevar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-thiyya", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-uppara", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-vaish", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-vaishnav", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-vaishnav-bhatia", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-vaishnav-bania", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-vaishya", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-valmiki", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-vania", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-vanjara", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-vannar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-vanniyar", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-vishwakarma", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-viswa-brahmin", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-vokaliga", 'attribute' => "community", 'type' => "string"),
            array('slug' => "community-vysya", 'attribute' => "community", 'type' => "string"),

            array('slug' => "pet-dogs", 'attribute' => "pet", 'type' => "string"),
            array('slug' => "pet-cats", 'attribute' => "pet", 'type' => "string"),
            array('slug' => "pet-other", 'attribute' => "pet", 'type' => "string"),
            array('slug' => "pet-dont-want", 'attribute' => "pet", 'type' => "string"),
            array('slug' => "pet-undecided", 'attribute' => "pet", 'type' => "string"),

            array('slug' => "education-finished-schooling", 'attribute' => "education", 'type' => "string"),
            array('slug' => "education-under-graduate", 'attribute' => "education", 'type' => "string"),
            array('slug' => "education-graduate", 'attribute' => "education", 'type' => "string"),
            array('slug' => "education-post-graduate", 'attribute' => "education", 'type' => "string"),
            array('slug' => "education-phd", 'attribute' => "education", 'type' => "string"),
            array('slug' => "education-preparing-for-entrance", 'attribute' => "education", 'type' => "string"),

            array('slug' => "university-college-gtu", 'attribute' => "university_college", 'type' => "string"),
            array('slug' => "university-college-osmania", 'attribute' => "university_college", 'type' => "string"),
            array('slug' => "university-college-university-of-delhi", 'attribute' => "university_college", 'type' => "string"),
            array('slug' => "university-college-university-of-pune", 'attribute' => "university_college", 'type' => "string"),
            array('slug' => "university-college-iim", 'attribute' => "university_college", 'type' => "string"),

            array('slug' => "profession-artist", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-business-analyst", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-designer", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-entrepreneur", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-freelancer", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-social-worker", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-doctor", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-nurse", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-teacher", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-blogger", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-vlogger", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-engineer", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-business", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-animator", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-film-maker", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-defense", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-writer", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-sports", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-farmer", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-stocks", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-crypto", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-ias", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-indian-armed-forces", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-govt", 'attribute' => "profession", 'type' => "string"),
            array('slug' => "profession-other", 'attribute' => "profession", 'type' => "string"),

            // array('slug' => "date-idea-take-a-long-walk-in-the-park", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-meet-for-breakfast", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-browse-a-bookstore", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-take-a-cooking-class", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-visit-an-outdoor-marke", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-plan-a-day-trip", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-go-for-a-picnic", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-take-a-painting-class", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-watch-a-movie", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-visit-an-museum", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-take-a-city-tour", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-take-an-adventurous-tour", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-visit-a-popular-restaurant", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-go-party-hopping", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-going-to-an-amusement-park", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-a-trip-to-an-ice-cream-store", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-a-day-at-the-zoo", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-playing-videogames-together", 'attribute' => "date_idea", 'type' => "string"),
            // array('slug' => "date-idea-listening-to-music-together", 'attribute' => "date_idea", 'type' => "string"),

            // array('slug' => "social-cause-educating-underprivileged-children-and-helping-them-grow", 'attribute' => "social_cause", 'type' => "string"),

            // array('slug' => "risk-taken-not-wearing-a-jacket-in-minus-10-degrees!", 'attribute' => "risk_taken", 'type' => "string"),

            // array('slug' => "perfect-relation-trust-laughter-and-understanding", 'attribute' => "perfect_relation_things", 'type' => "string"),

            // array('slug' => "my-mantra-live-and-let-live", 'attribute' => "my_mantra", 'type' => "string"),

            // array('slug' => "thing-about-me-i-love-jagjit-singh-so-be-ready-for-a-ghazal-session-on-our-dates!", 'attribute' => "thing_about_me", 'type' => "string"),

            // array('slug' => "worst-date-when-i-forgot-my-wallet-at-home", 'attribute' => "worst_date", 'type' => "string"),

            // array('slug' => "introduce-to-family-you-can-rock-a-traditional-outfit", 'attribute' => "introduce_to_family", 'type' => "string"),

            // array('slug' => "found-the-one-they-can-make-me-laugh-when-i-want-to-cry!", 'attribute' => "found_the_one", 'type' => "string"),

            // array('slug' => "about-me-surprises-i-have-never-had-a-pizza-in-my-life", 'attribute' => "about_me_surprises", 'type' => "string"),

            // array('slug' => "political-views-all-political-parties-divide-citizens-we-need-presidents-rule-in-the-country", 'attribute' => "political_views", 'type' => "string"),


            // array('slug' => "fav-festival-diwali", 'attribute' => "fav_festival", 'type' => "string"),
            // array('slug' => "fav-festival-holi", 'attribute' => "fav_festival", 'type' => "string"),
            // array('slug' => "fav-festival-christmas", 'attribute' => "fav_festival", 'type' => "string"),
            // array('slug' => "fav-festival-dussehra", 'attribute' => "fav_festival", 'type' => "string"),
            // array('slug' => "fav-festival-durga-puja", 'attribute' => "fav_festival", 'type' => "string"),
            // array('slug' => "fav-festival-ganesh-chaturthi", 'attribute' => "fav_festival", 'type' => "string"),
            // array('slug' => "fav-festival-eid-ul-fitr", 'attribute' => "fav_festival", 'type' => "string"),
            // array('slug' => "fav-festival-onam", 'attribute' => "fav_festival", 'type' => "string"),
            // array('slug' => "fav-festival-raksha-bandhan", 'attribute' => "fav_festival", 'type' => "string"),
            // array('slug' => "fav-festival-pongal", 'attribute' => "fav_festival", 'type' => "string"),
            // array('slug' => "fav-festival-gurupurab", 'attribute' => "fav_festival", 'type' => "string"),
            // array('slug' => "fav-festival-maha-shivratri", 'attribute' => "fav_festival", 'type' => "string"),
            // array('slug' => "fav-festival-lodi", 'attribute' => "fav_festival", 'type' => "string"),
            // array('slug' => "fav-festival-buddha-purnima", 'attribute' => "fav_festival", 'type' => "string"),
            // array('slug' => "fav-festival-makar-sankranti", 'attribute' => "fav_festival", 'type' => "string"),
        );

        ProfileDetail::insert($profile_detail);
    }
}
